# Generated by Django 4.1.1 on 2022-09-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Продукт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='webapp.category', verbose_name='Категория')),
            ],
        ),
    ]
